@Library('jenkins-shared-library@master') _
pipeline {
    agent {
        label 'terraform-build-agent'
    }
    
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select whether to apply or destroy infrastructure.')
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Terraform Credentials') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-jenkins-credentials', 
                        usernameVariable: 'AWS_ACCESS_KEY_ID', 
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    // You can add additional credential-related steps here if needed
                    sh 'echo "Credentials loaded securely"'
                }
            }
        }
        
        stage('Tflint') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                container('terraform') {
                    script {
                        tfLint('pipelines/project-02/ec2')
                    }
                }
            }
        }
        
        stage('Terraform Init') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-jenkins-credentials', 
                        usernameVariable: 'AWS_ACCESS_KEY_ID', 
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    withAWS(credentials: 'aws-jenkins-credentials', region: 'us-west-2') {
                        container('terraform') {
                            script {
                                terraform.init('pipelines/project-02/ec2', 'cat-jenkins-terraform', 'jenkins/terraform.tfstate', 'us-west-2')
                            }
                        }
                    }
                }
            }
        }
        
        // ... (rest of the pipeline remains the same)
    }
    
    post {
        always {
            script {
                emailNotification('sulaiman@crunchops.com')
            }
        }
    }
}
